### PR TITLE
Disable missing-column row group skipping

### PR DESCRIPTION
**Pull request by scovich**
## What changes are proposed in this pull request?

The optimization to treat a physically missing column as all-null is unsound, if the schema was not already verified to prove that the table's logical schema actually includes the missing column. Disable it until we can add the necessary validation. 

## How was this change tested?

New unit tests.

Fixes https://github.com/delta-incubator/delta-kernel-rs/issues/434

### CODE REVIEW

**Review by hntd187 — APPROVED** [review]
It is what it is, but LGTM

**Review by nicklan — APPROVED** [review]
lgtm! thanks for fixing quickly.

**Review by zachschuermann — APPROVED** [review]

**Comment by zachschuermann** [comment]
is `breaking-change` label/semver test broken? this shouldn't be breaking right? (and in CI i'm seeing some failures from changes not in this PR?)

cc @nicklan @scovich

**Comment by scovich** [comment]
> is `breaking-change` label/semver test broken? this shouldn't be breaking right? (and in CI i'm seeing some failures from changes not in this PR?)

I think it's just due to out of date base branch. I removed the label and will update; semver can re-add the label if this PR _really_ makes a breaking change.

**Pull request merged**
