### PR TITLE
Define and use a get_log_add_schema() function

### PR DESCRIPTION
**Pull request by scovich**
We have a convenient `get_log_schema()` function for accessing the Delta log schema, but many operations only need to access the `add` column. Replace clunky projection code with something direct and infallible, wrapped up as `get_log_add_schema()`. 

While we're at it, make both functions return `SchemaRef` instead of `Schema`, to reduce the number of deep clones needed (many use sites anyway need an arc).

### CODE REVIEW

**Review by zachschuermann — COMMENTED** [review]
just an overall question: do we want the `static LOG_*SCHEMA` to be an `Arc`? doesn't a static reference also implement the `Send`/`Sync`/etc. that we need? (and possibly marginally lighter weight?)

**Comment by scovich** [comment]
> just an overall question: do we want the `static LOG_*SCHEMA` to be an `Arc`? doesn't a static reference also implement the `Send`/`Sync`/etc. that we need? (and possibly marginally lighter weight?)

Rationale (from PR description):
> make both functions return `SchemaRef` instead of `Schema`, to reduce the number of deep clones needed (many use sites anyway need an arc).

Basically, it's easy/cheap to get a `&Schema` from an arc.. not so cheap to get an arc from a borrowed reference.

**Review by zachschuermann — APPROVED** [review]
LGTM

**Review by nicklan — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
