### PR TITLE
feat: add github action to self-assign the issue

### LINKED ISSUE #324: Create a take command to auto-assign issues
Here's an example of the take command in action: https://github.com/unitycatalog/unitycatalog/issues/284

Here's an example of the code that needs to be added: https://github.com/unitycatalog/unitycatalog/pull/188

### PR DESCRIPTION
**Pull request by tlm365**
Closes #324.

### CODE REVIEW

**Review by nicklan — COMMENTED** [review]
Thanks!

I have the same question as on the linked PR (https://github.com/unitycatalog/unitycatalog/pull/188/files#r1678081386)

Can we just do this in one step? If there's a good reason to split like this, I'm fine, I'd just like to know what it is :)

**Comment by tlm365** [comment]
> Thanks!
> 
> I have the same question as on the linked PR (https://github.com/unitycatalog/unitycatalog/pull/188/files#r1678081386)
> 
> Can we just do this in one step? If there's a good reason to split like this, I'm fine, I'd just like to know what it is :)

Absolutely yes :) I will update it.

**Comment by tlm365** [comment]
> naive question: is this useful since github permissions don't let people just add themselves as asignee?

I think the point here is **choice**. Instead of "open for take" by default, the repo's owner can choose to enable or disable it (github-action like this PR), as evidenced by the fact that GitHub still [supports this feature](https://docs.github.com/en/rest/issues/assignees?apiVersion=2022-11-28#add-assignees-to-an-issue). And I agree with @MrPowers that "`take` creates a good experience for OSS users"

**Comment by MrPowers** [comment]
@zachschuermann - let's say someone comes to this repo and wants to grab and issue to work on.

With this GitHub action, they can just comment "take" and then the action will auto-assign the issue to them.

Without this action, then they need to comment "Yes, I can work on this" and then we need to manually assign it to them.

This cuts out the manual step!

**Review by zachschuermann — APPROVED** [review]
lgtm! thanks!

**Review by nicklan — APPROVED** [review]
lgtm! thanks!

**Pull request merged**
