### PR TITLE
Define and use new AsAny trait

### PR DESCRIPTION
**Pull request by scovich**
## What changes are proposed in this pull request?

As part of implementing various kernel operations, engines need the ability to downcast kernel engine traits to their true concrete types. The rust `Any` trait can help with struct downcasting, but it isn't quite strong enough once traits are involved. For example, given `trait Foo: Any + Send + Sync`, and `struct Bar` that implements `Foo`, the following fails to compile:
```rust
let f: Arc<dyn Foo> = Arc::new(Bar);
let f: Arc<Bar> = f.downcast().unwrap(); // `Arc::downcast` method not found 
```
... as does this:
```rust
let f: Arc<Foo> = Arc::new(Foo{});
let a: Arc<dyn Any + Send + Sync> = f; // trait upcasting coercion is not stable rust
let f: Arc<Foo> = a.downcast().unwrap();
```

We solve the trait downcasting problem with a new `trait AsAny: Any + Send + Sync` -- automatically implemented for all `T: Any + Send + Sync` -- which defines methods for downcasting itself to `dyn Any + Send + Sync` (reference, box, or arc).

### This PR affects the following public APIs

The various engine traits (`ParquetHandler`, `EngineData`, etc.) are now constrained to be `AsAny` (which implies `Any + Send + Sync`) rather than merely `Send + Sync`). 

This change should be source compatible in the vast majority of cases, because most types implement `Any` automatically.

## How was this change tested?

Doc tests, and it also replaces similar special-case code in the arrow default engine data implementation.

### CODE REVIEW

**Comment by scovich** [comment]
Apparently our [codecov](https://app.codecov.io/gh/delta-incubator/delta-kernel-rs/pull/450#14dec605c7c2b22111467b021cc12ade) doesn't consider doc tests?
image

Because the doc test just a few lines above definitely exercises the supposedly not-covered method.

**Review by nicklan — APPROVED** [review]
Thanks, this will be useful

**Comment by zachschuermann** [comment]
regarding coverage of doctests I made an issue for us to follow up: https://github.com/delta-incubator/delta-kernel-rs/issues/484

**Review by zachschuermann — APPROVED** [review]
LGTM only question is does `AsAny` communicate enough information about our traits? Maybe consider calling `SendSyncAny` or something?

**Comment by scovich** [comment]
> LGTM only question is does `AsAny` communicate enough information about our traits? Maybe consider calling `SendSyncAny` or something?

I'm not sure the "fatter" name is really helpful? `AsAny` requires `Send+Sync` in order to support `Arc`, but I suppose we could do `AsAny + Send + Sync` at all the various sites just for extra clarity?

**Pull request merged**
