### PR TITLE
Clean up some more old table client references (replace with engine)

### PR DESCRIPTION
**Pull request by scovich**
Renames straggler [table] client references in the code, that escaped https://github.com/delta-incubator/delta-kernel-rs/pull/191.

### CODE REVIEW

**Comment by scovich** [comment]
Looks like I may have somehow broken cbindgen? (but it seems to run fine if I invoke it manually?)
```
gcc -I../target/ffi-headers -c -Wall -DDEFINE_DEFAULT_ENGINE  -fPIC cffi-test.c -o cffi-test.o
cffi-test.c:5:10: fatal error: 'delta_kernel_ffi.h' file not found
#include "delta_kernel_ffi.h"
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [cffi-test.o] Error 1
```

**Review by nicklan — APPROVED** [review]
thanks!

**Comment by scovich** [comment]
> > Looks like I may have somehow broken cbindgen? (but it seems to run fine if I invoke it manually?)
> 
> Are you sure you ran `cargo build` before `make`?

I had accidentally disabled build.rs...

**Comment by hntd187** [comment]
LGMT

**Review by hntd187 — APPROVED** [review]

**Pull request merged**
